#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase

# Remove surface and features
rm particle_*.vtu
rm mesh.vtk
rm mesh_faces.vtk

#------------------------------------------------------------------------------
