export RTX=false
export OptiX_INSTALL_DIR=${HOME}/cudaParticlesFoam/NVIDIA-OptiX-SDK-7.0.0-linux64
export CUDA_HOME=/usr/local/cuda-10.1

alias runWithDocker="docker run -e NVIDIA_DRIVER_CAPABILITIES=graphics,compute \
  --rm -it -v \${PWD}:/sim --gpus all ghcr.io/simzero-oss/cudaparticlesfoam-rt:v0.1"
